Variable declaration, data types, numbers
IrinaMaslyukova/js-basic pull request #1
Opened 2019-10-15 07:49 UTC by IrinaMaslyukova

2019-10-17 18:19 UTC, lizarusi requested changes

2019-10-17 18:19 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +a = typeof ('Hello');
you need to run it on variables that you should create above, not just reassigning `a`

2019-10-17 18:19 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +a = typeof ({
no need to assign to `a` result of typeof

2019-10-17 18:19 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +const copyValue = {...obj};
you are demonstrating how to workaround references :)

2019-10-17 18:19 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  return parseInt(num);
mention that float numbers can appear

2019-10-17 18:19 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +console.log(parseInt(str_1, 2));
no need to parse them again

2019-10-17 18:19 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +let a = Math.round(Math.random());
you need to generate random value from 0 to 100. you are generating from 0 to 1

2019-10-17 18:19 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +let num = new Number(10);
always use `const` when variable not going to be change

2019-10-27 18:07 UTC, Mike-Savin requested changes

2019-10-27 18:07 UTC, Mike-Savin commented on Exercises/data-types-overview/data-types-overview.js
> +let a_1 = new Number(123);
Javascript variables should have names in camelCase, not in snake_case.

2019-10-27 18:07 UTC, Mike-Savin commented on Exercises/data-types-overview/data-types-overview.js
> +  typeof (c_1), typeof (d), typeof (e), typeof (f), typeof (g));
You don't need brackets after typeof.

2019-10-27 18:07 UTC, Mike-Savin commented on Exercises/numbers/numbers.js
> +  console.log(num);
`new Number(x)` creates number with value x, not a value in x format.

2019-10-27 18:07 UTC, Mike-Savin commented on Exercises/numbers/numbers.js
> +let str_1 = num.toString(2);
names should be in camelCase

2019-10-27 18:07 UTC, Mike-Savin commented on Exercises/numbers/numbers.js
> +const min = 1
Don't miss `;` at the end of the string

2019-11-01 13:16 UTC, Mike-Savin requested changes
see my comments

2019-11-20 14:00 UTC, merged